# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 570)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 570))
        MainWindow.setMaximumSize(QtCore.QSize(900, 570))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Barbaris.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addProjBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addProjBtn.setGeometry(QtCore.QRect(10, 10, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addProjBtn.setFont(font)
        self.addProjBtn.setObjectName("addProjBtn")
        self.openGGCBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openGGCBtn.setGeometry(QtCore.QRect(700, 80, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.openGGCBtn.setFont(font)
        self.openGGCBtn.setObjectName("openGGCBtn")
        self.openIDEBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openIDEBtn.setGeometry(QtCore.QRect(700, 150, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.openIDEBtn.setFont(font)
        self.openIDEBtn.setObjectName("openIDEBtn")
        self.openCalcBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openCalcBtn.setGeometry(QtCore.QRect(700, 220, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.openCalcBtn.setFont(font)
        self.openCalcBtn.setObjectName("openCalcBtn")
        self.openPngIcoConBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openPngIcoConBtn.setGeometry(QtCore.QRect(700, 290, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.openPngIcoConBtn.setFont(font)
        self.openPngIcoConBtn.setObjectName("openPngIcoConBtn")
        self.openConfBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openConfBtn.setGeometry(QtCore.QRect(700, 360, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.openConfBtn.setFont(font)
        self.openConfBtn.setObjectName("openConfBtn")
        self.projPane = QtWidgets.QListWidget(self.centralwidget)
        self.projPane.setGeometry(QtCore.QRect(10, 80, 681, 481))
        self.projPane.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.projPane.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.projPane.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.projPane.setAlternatingRowColors(False)
        self.projPane.setObjectName("projPane")
        self.confProjsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.confProjsBtn.setGeometry(QtCore.QRect(210, 10, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.confProjsBtn.setFont(font)
        self.confProjsBtn.setObjectName("confProjsBtn")
        self.updBtn = QtWidgets.QPushButton(self.centralwidget)
        self.updBtn.setGeometry(QtCore.QRect(410, 10, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.updBtn.setFont(font)
        self.updBtn.setObjectName("updBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Barbaris Launcher"))
        self.addProjBtn.setText(_translate("MainWindow", "Добавить проект"))
        self.openGGCBtn.setText(_translate("MainWindow", "Открыть GGC"))
        self.openIDEBtn.setText(_translate("MainWindow", "Открыть IDE"))
        self.openCalcBtn.setText(_translate("MainWindow", "Открыть\n"
"Калькулятор"))
        self.openPngIcoConBtn.setText(_translate("MainWindow", "Открыть png-ico\n"
" конвертор"))
        self.openConfBtn.setText(_translate("MainWindow", "Открыть\n"
"конфигуратор путей"))
        self.confProjsBtn.setText(_translate("MainWindow", "Редактировать"))
        self.updBtn.setText(_translate("MainWindow", "Обновить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
