# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjsConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_conf_projs_window(object):
    def setupUi(self, conf_projs_window):
        conf_projs_window.setObjectName("conf_projs_window")
        conf_projs_window.resize(509, 421)
        self.centralwidget = QtWidgets.QWidget(conf_projs_window)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 40, 511, 381))
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        conf_projs_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(conf_projs_window)
        QtCore.QMetaObject.connectSlotsByName(conf_projs_window)

    def retranslateUi(self, conf_projs_window):
        _translate = QtCore.QCoreApplication.translate
        conf_projs_window.setWindowTitle(_translate("conf_projs_window", "Удаление проектов"))
        self.label.setText(_translate("conf_projs_window", "Нажмите на проект, чтобы удалить его"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    conf_projs_window = QtWidgets.QMainWindow()
    ui = Ui_conf_projs_window()
    ui.setupUi(conf_projs_window)
    conf_projs_window.show()
    sys.exit(app.exec_())
